/* Generated By:JavaCC: Do not edit this line. Compilador.java */
package parser;

import jasmin.*;
import java.io.*;
import semantico.*;
import apoio.*;
import tratamentoErro.*;
import comandoAltoNivel.*;
import comandoPrimitivo.*;
import codigoDestino.*;
import java.util.LinkedList;


public class Compilador implements CompiladorConstants {
        public static Tabela tabelaPrograma = new Tabela( Config.nomeArquivo );
        // Argumentos para o jasmin gerar automaticamente o .class na pasta saida
        public static String arquivo[] = { "-d", Config.pathSaida, Config.pathSaida + Config.nomeArquivo + Config.extensaoCodigoDestino };
        public static String imageMain = Compilador.tokenImage[Compilador.MAIN];

        public static void main(String args[])  throws ParseException  {
                Compilador compilador = null;
                imageMain = imageMain.substring(1, imageMain.length()-1);

                try {
                        // Leitura do arquivo com o codigo fonte
                        compilador = new Compilador(new FileInputStream(Config.pathProgFonte + Config.nomeArquivo + Config.extensaoFonte));

                        // Primeira passagem
                        ListaComandosAltoNivel listaComandosAltoNivel = new ListaComandosAltoNivel();
                        Compilador.inicio(listaComandosAltoNivel);

                        System.out.println("***** Primeira Passagem *****\u005cn"
                                                                + "Lista de Comandos Alto Nivel:\u005cn"
                                                                + listaComandosAltoNivel);

                        // Exibicao da tabela de simbolos
                        System.out.println("\u005cn\u005cn***** Tabela de Simbolos *****\u005cn"
                                                                + tabelaPrograma );

                        //Warnings
                        AcoesSemanticas.warnings();

                        // Segunda passagem
                        ListaComandosPrimitivos listaComandosPrimitivos = new ListaComandosPrimitivos();
                        listaComandosPrimitivos = listaComandosAltoNivel.geraListaComandoPrimitivosCompleta();
                        System.out.println("\u005cn\u005cn***** Segunda Passagem *****\u005cn"
                                                                + "Lista de Comandos Primitivos:\u005cn"
                                                                + listaComandosPrimitivos);

                        // Terceira passagem
                        CodigoDestino codigoDestino = new CodigoDestino(listaComandosPrimitivos);
                        System.out.println("\u005cn\u005cn***** Terceira Passagem *****\u005cn"
                                                                + "Lista de Comandos Destino:\u005cn"
                                                                + codigoDestino);

                        // Criacao do arquivo destino
                        codigoDestino.geraArquivo(Config.pathSaida + Config.nomeArquivo + Config.extensaoCodigoDestino );
                        System.out.println("\u005cn\u005cn***** Criacao do arquivo destino *****\u005cn"
                                                                + "Arquivo destino: "
                                                                + Config.pathSaida + Config.nomeArquivo + Config.extensaoCodigoDestino);

                        // Fim
                        if(AcoesSemanticas.qtdWarnings > 0 ) {
                          System.out.println("\u005cn\u005cn***** Compilacao bem sucedida com "+AcoesSemanticas.qtdWarnings+" warnings! *****");
                        }else {
                                System.out.println("\u005cn\u005cn***** Compilacao bem sucedida! *****");
                        }

                        // Geracao automatizada do .class na pasta saida
                        Main.main(arquivo);

                }

                catch(FileNotFoundException e) {
                        System.err.println("\u005cnErro: arquivo nao encontrado");
                }
                catch (IOException e) {
                        System.out.println("Erro de criacao de arquivo" + e.getMessage());
                }
                catch(TokenMgrError e) {
                        System.err.println("\u005cnErro lexico: " + e.getMessage());
                }
                catch(ParseException e) {
                        System.err.println("\u005cnErro Sintatico: " + e.getMessage());
                }
                catch(ErroSemantico e) {
                        System.err.println("\u005cnErro Semantico: " + e.getMessage());
                }
        }

//Gramatica de expressoes:
  static final public Expressao iniciaExpressao(Tabela tabela) throws ParseException {
        Expressao exp = new Expressao( tabela.getNome() );
    expressao(exp, tabela);
            exp.otimizarPosFixaConst1();
                exp.otimizaPosfixa();
                exp.otimizarNegacao();
//        exp.otimizarOperacoesConstantes();
                {if (true) return exp;}
    throw new Error("Missing return statement in function");
  }

  static final public void expressao(Expressao exp, Tabela tabela) throws ParseException {
        Token t ;
        Item item = null;
    termo(exp, tabela);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OU:
      case OUEXCLUSIVO:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OU:
        t = jj_consume_token(OU);
                       item = new Operador(TipoOperador.OU,t);
        break;
      case OUEXCLUSIVO:
        t = jj_consume_token(OUEXCLUSIVO);
                                   item = new Operador(TipoOperador.OUEXCLUSIVO,t);
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                        exp.addListaExpInfixa(item);
      termo(exp, tabela);
                        exp.addListaExpPosFixa(item);
    }
  }

  static final public void termo(Expressao exp, Tabela tabela) throws ParseException {
        Token t;
        Item item = null;
    termo1(exp, tabela);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case E:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      t = jj_consume_token(E);
                        item = new Operador(TipoOperador.E,t);
                        exp.addListaExpInfixa(item);
      termo1(exp, tabela);
                        exp.addListaExpPosFixa(item);
    }
  }

  static final public void termo1(Expressao exp, Tabela tabela) throws ParseException {
        Token t;
        Item item = null;
        TipoOperador operador;
    negacao(exp, tabela);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IGUAL:
    case DIFERENTE:
    case MENOR:
    case MAIORIGUAL:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IGUAL:
        t = jj_consume_token(IGUAL);
                               operador = TipoOperador.IGUAL;
        break;
      case DIFERENTE:
        t = jj_consume_token(DIFERENTE);
                                       operador = TipoOperador.DIFERENTE;
        break;
      case MENOR:
        t = jj_consume_token(MENOR);
                                   operador = TipoOperador.MENOR;
        break;
      case MAIORIGUAL:
        t = jj_consume_token(MAIORIGUAL);
                                       operador = TipoOperador.MAIORIGUAL;
        break;
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                        item = new Operador(operador,t);
                        exp.addListaExpInfixa(item);
      negacao(exp, tabela);
                        item = new Operador(operador,t);
                        exp.addListaExpPosFixa(item);
      break;
    default:
      jj_la1[4] = jj_gen;
      ;
    }
  }

  static final public void negacao(Expressao exp, Tabela tabela) throws ParseException {
        Token t;
        Item item = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MAX:
    case MIN:
    case NUM:
    case SOMA:
    case SUB:
    case LOG:
    case PISO:
    case TETO:
    case AP:
    case STRING:
    case VAR:
      termo2(exp, tabela);
      break;
    case NEGACAO:
      t = jj_consume_token(NEGACAO);
                        item = new Operador(TipoOperador.NEGACAO,t);
                        exp.addListaExpInfixa(item);
      negacao(exp, tabela);
                        exp.addListaExpPosFixa(item);
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void termo2(Expressao exp, Tabela tabela) throws ParseException {
        Token t;
        Item item = null;
    termo3(exp, tabela);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CONCAT:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_3;
      }
      t = jj_consume_token(CONCAT);
                        item = new Operador(TipoOperador.CONCAT,t);
                        exp.addListaExpInfixa(item);
      termo3(exp, tabela);
                        item = new Operador(TipoOperador.CONCAT,t);
                        exp.addListaExpPosFixa(item);
    }
  }

  static final public void termo3(Expressao exp, Tabela tabela) throws ParseException {
        Token t;
        TipoOperador operador;
        Item item = null;
    termo4(exp, tabela);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOMA:
      case SUB:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOMA:
        t = jj_consume_token(SOMA);
                                operador = TipoOperador.SOMA;
        break;
      case SUB:
        t = jj_consume_token(SUB);
                               operador = TipoOperador.SUB;
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                        item = new Operador(operador,t);
                        exp.addListaExpInfixa(item);
      termo4(exp, tabela);
                        item = new Operador(operador,t);
                        exp.addListaExpPosFixa(item);
    }
  }

  static final public void termo4(Expressao exp, Tabela tabela) throws ParseException {
        Token t;
        TipoOperador operador;
        Item item = null;
    pot(exp, tabela);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MUL:
      case DIV:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MUL:
        t = jj_consume_token(MUL);
                              operador = TipoOperador.MUL;
        break;
      case DIV:
        t = jj_consume_token(DIV);
                              operador = TipoOperador.DIV;
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                        item = new Operador(operador,t);
                        exp.addListaExpInfixa(item);
      pot(exp, tabela);
                        item = new Operador(operador,t);
                        exp.addListaExpPosFixa(item);
    }
  }

  static final public void pot(Expressao exp, Tabela tabela) throws ParseException {
        Token t;
        TipoOperador operador;
        Item item = null;
    log(exp, tabela);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case POT:
      t = jj_consume_token(POT);
                    operador = TipoOperador.POT;
                item = new Operador(operador, t);
            exp.addListaExpInfixa(item);
      pot(exp, tabela);
                item = new Operador(operador, t);
            exp.addListaExpPosFixa(item);
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
  }

  static final public void log(Expressao exp, Tabela tabela) throws ParseException {
        Token t;
        TipoOperador operador;
        Item item = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUM:
    case SOMA:
    case SUB:
    case AP:
    case STRING:
    case VAR:
      termo5(exp, tabela);
      break;
    case MAX:
    case MIN:
    case LOG:
    case PISO:
    case TETO:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LOG:
      case PISO:
      case TETO:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LOG:
          t = jj_consume_token(LOG);
                        operador = TipoOperador.LOG;
          break;
        case PISO:
          t = jj_consume_token(PISO);
                             operador = TipoOperador.PISO;
          break;
        case TETO:
          t = jj_consume_token(TETO);
                             operador = TipoOperador.TETO;
          break;
        default:
          jj_la1[12] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(AP);
        expressao(exp,tabela);
        jj_consume_token(FP);
        break;
      case MAX:
      case MIN:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MAX:
          t = jj_consume_token(MAX);
                        operador = TipoOperador.MAX;
          break;
        case MIN:
          t = jj_consume_token(MIN);
                        operador = TipoOperador.MIN;
          break;
        default:
          jj_la1[13] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(AP);
        expressao(exp, tabela);
        jj_consume_token(VIRGULA);
        expressao(exp, tabela);
        jj_consume_token(FP);
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
        item = new Operador(operador, t);
        exp.addListaExpInfixa(item);
        exp.addListaExpPosFixa(item);
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void termo5(Expressao exp, Tabela tabela) throws ParseException {
        Token tokenVar, tokenEntrada;
        Item item = null;
        Sinal sinal = Sinal.POS;
        LinkedList<Expressao> listaParam = new LinkedList<Expressao>();
        Expressao expParam;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AP:
      tokenEntrada = jj_consume_token(AP);
                item = new Operador(TipoOperador.AP, tokenEntrada);
                exp.addListaExpInfixa(item);
      expressao(exp, tabela);
      tokenEntrada = jj_consume_token(FP);
                item = new Operador(TipoOperador.FP, tokenEntrada);
                exp.addListaExpInfixa(item);
      break;
    case NUM:
    case SOMA:
    case SUB:
    case VAR:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOMA:
      case SUB:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SUB:
          jj_consume_token(SUB);
                      sinal = Sinal.NEG;
          break;
        case SOMA:
          jj_consume_token(SOMA);
                                                      sinal = Sinal.POS;
          break;
        default:
          jj_la1[16] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[17] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        tokenEntrada = jj_consume_token(NUM);
                                item = new Operando(TipoDado.NUMERO,TipoElemento.CTE, tokenEntrada, sinal);
                                AcoesSemanticas.incompatibilidadeTipoExpressao(item,exp,tokenEntrada);
                                exp.addListaExpInfixa(item);
                                exp.addListaExpPosFixa(item);
        break;
      case VAR:
        tokenVar = jj_consume_token(VAR);
                                              item = new Operando(tabela.tipoVariavel(tokenVar.image),TipoElemento.VAR, tokenVar, sinal);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AP:
          jj_consume_token(AP);
          expParam = iniciaExpressao(tabela);
                                                                       listaParam.add( expParam );
          label_6:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case VIRGULA:
              ;
              break;
            default:
              jj_la1[18] = jj_gen;
              break label_6;
            }
            jj_consume_token(VIRGULA);
            expParam = iniciaExpressao(tabela);
                                                                                       listaParam.add( expParam );
          }
          jj_consume_token(FP);
                                          item = new ChamadaFuncao( TipoOperador.FUNCAO, tokenVar, tokenVar, listaParam );
                                          //tabela.pesquisarSimboloTabela(tokenVar.image).setIsUtilizada(true);

          break;
        default:
          jj_la1[19] = jj_gen;
          ;
        }
//					tabela.verificaVariavelDeclarada(tokenVar.image);
//					AcoesSemanticas.incompatibilidadeTipoExpressao(item,exp,tokenVar);
                                        exp.addListaExpInfixa(item);
                                        exp.addListaExpPosFixa(item);
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case STRING:
      tokenEntrada = jj_consume_token(STRING);
                item = new Operando(TipoDado.PALAVRA,TipoElemento.CTE, tokenEntrada, Sinal.POS);
                AcoesSemanticas.incompatibilidadeTipoExpressao(item,exp,tokenEntrada);
                exp.addListaExpInfixa(item);
                exp.addListaExpPosFixa(item);
      break;
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//GRAMATICA COMPLETA
  static final public void inicio(ListaComandosAltoNivel listaComandosAltoNivel) throws ParseException {
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FUNCAO:
      case PROCEDIMENTO:
      case COMENTLINHA:
        ;
        break;
      default:
        jj_la1[22] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMENTLINHA:
        jj_consume_token(COMENTLINHA);
        break;
      case PROCEDIMENTO:
        procedimento(listaComandosAltoNivel);
        break;
      case FUNCAO:
        funcao(listaComandosAltoNivel);
        break;
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
          AcoesSemanticas.verificarExistenciaMetodoMain();
    jj_consume_token(0);
  }

  static final public void procedimento(ListaComandosAltoNivel listaComandosAltoNivel) throws ParseException {
  Token tokenProcedimento, tokenAssinatura, tokenVar;
  LinkedList<Token> listaParametros = new LinkedList<Token>();
  TipoDado tipoParam;
  ComandoAltoNivel comando;
  ListaComandosAltoNivel listaCorpoProcedimento = new ListaComandosAltoNivel();
    tokenProcedimento = jj_consume_token(PROCEDIMENTO);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VAR:
      tokenAssinatura = jj_consume_token(VAR);
      break;
    case MAIN:
      tokenAssinatura = jj_consume_token(MAIN);
      break;
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                                                               Compilador.tabelaPrograma.insereNamespaceNaTabela( tokenAssinatura, TipoOperador.PROCEDIMENTO );
    jj_consume_token(AP);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMERO:
    case PALAVRA:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PALAVRA:
        jj_consume_token(PALAVRA);
                        tipoParam =  TipoDado.PALAVRA;
        break;
      case NUMERO:
        jj_consume_token(NUMERO);
                                                                        tipoParam =  TipoDado.NUMERO;
        break;
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      tokenVar = jj_consume_token(VAR);
          Compilador.tabelaPrograma.pesquisarTabela( tokenAssinatura.image ).insereSimboloNaTabela( tokenVar, tipoParam);
          Compilador.tabelaPrograma.pesquisarTabela( tokenAssinatura.image ).pesquisarSimboloTabela( tokenVar.image ).setIsInicializada(true);
          listaParametros.add( tokenVar );
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case VIRGULA:
          ;
          break;
        default:
          jj_la1[26] = jj_gen;
          break label_8;
        }
        jj_consume_token(VIRGULA);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NUMERO:
        case PALAVRA:
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PALAVRA:
            jj_consume_token(PALAVRA);
                                       tipoParam =  TipoDado.PALAVRA;
            break;
          case NUMERO:
            jj_consume_token(NUMERO);
                                                                                     tipoParam =  TipoDado.NUMERO;
            break;
          default:
            jj_la1[27] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
        default:
          jj_la1[28] = jj_gen;
          ;
        }
        tokenVar = jj_consume_token(VAR);
                Compilador.tabelaPrograma.pesquisarTabela( tokenAssinatura.image ).insereSimboloNaTabela( tokenVar, tipoParam);
                Compilador.tabelaPrograma.pesquisarTabela( tokenAssinatura.image ).pesquisarSimboloTabela( tokenVar.image ).setIsInicializada(true);
                listaParametros.add( tokenVar );
      }
      break;
    default:
      jj_la1[29] = jj_gen;
      ;
    }
    jj_consume_token(FP);
    programa(listaCorpoProcedimento, Compilador.tabelaPrograma.pesquisarTabela( tokenAssinatura.image ));
                                                                                                                AcoesSemanticas.otimizarComandosCondicionais( listaCorpoProcedimento );
    jj_consume_token(FIMPROCEDIMENTO);
                comando = new Procedimento( tokenProcedimento, tokenAssinatura, listaParametros, listaCorpoProcedimento );
                listaComandosAltoNivel.addComando( comando );
  }

  static final public void funcao(ListaComandosAltoNivel listaComandosAltoNivel) throws ParseException {
  Token tokenFuncao, tokenAssinatura, tokenVar;
  LinkedList<Token> listaParametros = new LinkedList<Token>();
  TipoDado tipoParam, tipoRetorno;
  ComandoAltoNivel comando;
  ListaComandosAltoNivel listaCorpoProcedimento = new ListaComandosAltoNivel();
    tokenFuncao = jj_consume_token(FUNCAO);
    tokenAssinatura = jj_consume_token(VAR);
                                  Compilador.tabelaPrograma.insereNamespaceNaTabela( tokenAssinatura, TipoOperador.FUNCAO );
    jj_consume_token(AP);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMERO:
    case PALAVRA:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PALAVRA:
        jj_consume_token(PALAVRA);
                        tipoParam =  TipoDado.PALAVRA;
        break;
      case NUMERO:
        jj_consume_token(NUMERO);
                                                                        tipoParam =  TipoDado.NUMERO;
        break;
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      tokenVar = jj_consume_token(VAR);
          Compilador.tabelaPrograma.pesquisarTabela( tokenAssinatura.image ).insereSimboloNaTabela( tokenVar, tipoParam);
          Compilador.tabelaPrograma.pesquisarTabela( tokenAssinatura.image ).pesquisarSimboloTabela( tokenVar.image ).setIsInicializada(true);
          listaParametros.add( tokenVar );
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case VIRGULA:
          ;
          break;
        default:
          jj_la1[31] = jj_gen;
          break label_9;
        }
        jj_consume_token(VIRGULA);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NUMERO:
        case PALAVRA:
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PALAVRA:
            jj_consume_token(PALAVRA);
                                       tipoParam =  TipoDado.PALAVRA;
            break;
          case NUMERO:
            jj_consume_token(NUMERO);
                                                                                     tipoParam =  TipoDado.NUMERO;
            break;
          default:
            jj_la1[32] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
        default:
          jj_la1[33] = jj_gen;
          ;
        }
        tokenVar = jj_consume_token(VAR);
                Compilador.tabelaPrograma.pesquisarTabela( tokenAssinatura.image ).insereSimboloNaTabela( tokenVar, tipoParam);
                Compilador.tabelaPrograma.pesquisarTabela( tokenAssinatura.image ).pesquisarSimboloTabela( tokenVar.image ).setIsInicializada(true);
                listaParametros.add( tokenVar );
      }
      break;
    default:
      jj_la1[34] = jj_gen;
      ;
    }
    jj_consume_token(FP);
    jj_consume_token(DP);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMERO:
      jj_consume_token(NUMERO);
                               tipoRetorno = TipoDado.NUMERO;
      break;
    case PALAVRA:
      jj_consume_token(PALAVRA);
                                                                              tipoRetorno = TipoDado.PALAVRA;
      break;
    default:
      jj_la1[35] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                Compilador.tabelaPrograma.pesquisarTabela( tokenAssinatura.image ).setTipoRetorno( tipoRetorno );
    programa(listaCorpoProcedimento, Compilador.tabelaPrograma.pesquisarTabela( tokenAssinatura.image ));
                                                                                                                AcoesSemanticas.otimizarComandosCondicionais( listaCorpoProcedimento );
    jj_consume_token(FIMFUNCAO);
                comando = new Funcao( tokenFuncao, tokenAssinatura, listaParametros, listaCorpoProcedimento, tipoRetorno );
                listaComandosAltoNivel.addComando( comando );
  }

  static final public void retorne(ListaComandosAltoNivel listaComandosAltoNivel, Tabela tabela) throws ParseException {
  Token tokenRetorne;
  Expressao expressao;
  ComandoAltoNivel comandoRetorne;
    tokenRetorne = jj_consume_token(RETORNE);
    expressao = iniciaExpressao(tabela);
                comandoRetorne = new ComandoRetorne( tokenRetorne, expressao );
                listaComandosAltoNivel.addComando( comandoRetorne );
  }

  static final public void programa(ListaComandosAltoNivel listaComandosAltoNivel, Tabela tabela) throws ParseException {
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EXIBE:
      case LEITURA:
      case LEITURACOMPLETA:
      case SE:
      case ENQUANTO:
      case PARA:
      case SELETOR:
      case FACA:
      case REPEAT:
      case SEREPETE:
      case DUPLO:
      case MATRIX3D:
      case RETORNE:
      case COMENTLINHA:
      case NUMERO:
      case PALAVRA:
      case EXIBELN:
      case AP:
      case VAR:
        ;
        break;
      default:
        jj_la1[36] = jj_gen;
        break label_10;
      }
      comando(listaComandosAltoNivel, tabela);
    }
  }

  static final public void comando(ListaComandosAltoNivel listaComandosAltoNivel, Tabela tabela) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMENTLINHA:
    case NUMERO:
    case PALAVRA:
    case VAR:
      comandoInstanciacao(listaComandosAltoNivel, tabela);
      break;
    case SE:
      se(listaComandosAltoNivel, tabela);
      break;
    case ENQUANTO:
      enquanto(listaComandosAltoNivel, tabela);
      break;
    case LEITURA:
    case LEITURACOMPLETA:
      le(listaComandosAltoNivel, tabela);
      break;
    case EXIBE:
    case EXIBELN:
      exibe(listaComandosAltoNivel, tabela);
      break;
    case PARA:
      para(listaComandosAltoNivel, tabela);
      break;
    case SELETOR:
      seletor(listaComandosAltoNivel, tabela);
      break;
    case FACA:
      fazerEnquanto(listaComandosAltoNivel, tabela);
      break;
    case REPEAT:
      repeat(listaComandosAltoNivel, tabela);
      break;
    case SEREPETE:
      seRepete(listaComandosAltoNivel, tabela);
      break;
    case DUPLO:
      duplo(listaComandosAltoNivel, tabela);
      break;
    case MATRIX3D:
      matrix3D(listaComandosAltoNivel, tabela);
      break;
    case AP:
      ternario(listaComandosAltoNivel, tabela);
      break;
    case RETORNE:
      retorne(listaComandosAltoNivel, tabela);
      jj_consume_token(PV);
      break;
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void comandoInstanciacao(ListaComandosAltoNivel listaComandosAltoNivel, Tabela tabela) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VAR:
      atribuicaoChamada(listaComandosAltoNivel, tabela);
      jj_consume_token(PV);
      break;
    case NUMERO:
    case PALAVRA:
      declaracao(listaComandosAltoNivel, tabela);
      break;
    case COMENTLINHA:
      jj_consume_token(COMENTLINHA);
      break;
    default:
      jj_la1[38] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void atribuicaoChamada(ListaComandosAltoNivel listaComandosAltoNivel, Tabela tabela) throws ParseException {
        Token atrib, var;
        LinkedList<Expressao > listaExp = new LinkedList<Expressao >();
    var = jj_consume_token(VAR);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SOMA:
    case SUB:
    case MUL:
    case DIV:
    case ATRIB:
    case ATRIBMULT:
    case VIRGULA:
      atribuicao(listaComandosAltoNivel, var, tabela);
      break;
    case AP:
      chamadaProcedimentoFuncao(listaComandosAltoNivel, var, tabela);
      break;
    default:
      jj_la1[39] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void chamadaProcedimentoFuncao(ListaComandosAltoNivel listaComandosAltoNivel, Token tokenAssinatura, Tabela tabela) throws ParseException {
  Token tokenVar;
  LinkedList<Expressao> listaParametros = new LinkedList<Expressao>();
  ComandoAltoNivel comando;
  Expressao expressaoParam;
    jj_consume_token(AP);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MAX:
    case MIN:
    case NUM:
    case SOMA:
    case SUB:
    case LOG:
    case PISO:
    case TETO:
    case NEGACAO:
    case AP:
    case STRING:
    case VAR:
      expressaoParam = iniciaExpressao(tabela);
                                                             listaParametros.add( expressaoParam );
      label_11:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case VIRGULA:
          ;
          break;
        default:
          jj_la1[40] = jj_gen;
          break label_11;
        }
        jj_consume_token(VIRGULA);
        expressaoParam = iniciaExpressao(tabela);
                                                                                         listaParametros.add( expressaoParam );
      }
      break;
    default:
      jj_la1[41] = jj_gen;
      ;
    }
    jj_consume_token(FP);
                AcoesSemanticas.verificarExistenciaMetodo( tokenAssinatura );
                comando = new ChamadaMetodo( tokenAssinatura, listaParametros );
                listaComandosAltoNivel.addComando( comando );
  }

  static final public void atribuicao(ListaComandosAltoNivel listaComandosAltoNivel, Token Var, Tabela tabela) throws ParseException {
        Token atrib, var = Var;
        TipoOperador tpOperador;
        Item operando, operador;
//	ComandoAltoNivel comando = null;
        Expressao expressao = null;
        LinkedList<Token > listaVar = new LinkedList<Token >();
        listaVar.add(Var);
        LinkedList<Expressao > listaExp = new LinkedList<Expressao >();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ATRIB:
    case ATRIBMULT:
    case VIRGULA:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ATRIB:
        atrib = jj_consume_token(ATRIB);
        expressao = iniciaExpressao(tabela);
                                                                   listaExp.add( expressao);
        break;
      case ATRIBMULT:
      case VIRGULA:
        label_12:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case VIRGULA:
            ;
            break;
          default:
            jj_la1[42] = jj_gen;
            break label_12;
          }
          jj_consume_token(VIRGULA);
          var = jj_consume_token(VAR);
                                            tabela.verificaVariavelDeclarada(var.image); listaVar.add(var);
        }
        atrib = jj_consume_token(ATRIBMULT);
        expressao = iniciaExpressao(tabela);
                                                                     listaExp.add( expressao );
        label_13:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case VIRGULA:
            ;
            break;
          default:
            jj_la1[43] = jj_gen;
            break label_13;
          }
          jj_consume_token(VIRGULA);
          expressao = iniciaExpressao(tabela);
                                                                      listaExp.add( expressao );
        }
        break;
      default:
        jj_la1[44] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                 AcoesSemanticas.verificarParesAtribuicaoMultipla( listaVar, listaExp, atrib );
                 AcoesSemanticas.gerarAtribuicoesMultiplas( listaComandosAltoNivel, tabela, listaVar, listaExp, atrib );
      break;
    case SOMA:
    case SUB:
    case MUL:
    case DIV:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOMA:
        atrib = jj_consume_token(SOMA);
                             tpOperador = TipoOperador.SOMA;
        break;
      case SUB:
        atrib = jj_consume_token(SUB);
                           tpOperador = TipoOperador.SUB;
        break;
      case MUL:
        atrib = jj_consume_token(MUL);
                           tpOperador = TipoOperador.MUL;
        break;
      case DIV:
        atrib = jj_consume_token(DIV);
                           tpOperador = TipoOperador.DIV;
        break;
      default:
        jj_la1[45] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
           operador = new Operador( tpOperador, atrib );
       operando = new Operando( tabela.tipoVariavel(var.image), TipoElemento.VAR, var, Sinal.POS );
       expressao = new Expressao(tabela.getNome());
       expressao.addListaExpInfixa( operando );
       expressao.addListaExpInfixa( operador );
       expressao.addListaExpPosFixa( operando );
      jj_consume_token(IGUAL);
      expressao(expressao, tabela);
                expressao.addListaExpPosFixa( operador );
                listaComandosAltoNivel.addComando( new ComandoAtribuicao( tabela.pesquisarSimboloTabela(var.image), expressao, atrib ) );
      break;
    default:
      jj_la1[46] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void declaracao(ListaComandosAltoNivel listaComandosAltoNivel, Tabela tabela) throws ParseException {
        Token atrib, variavel;
        TipoDado tipo = null;
        ComandoAltoNivel comando = null;
        Expressao expressao = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMERO:
      jj_consume_token(NUMERO);
                      tipo = TipoDado.NUMERO;
      break;
    case PALAVRA:
      jj_consume_token(PALAVRA);
                       tipo = TipoDado.PALAVRA;
      break;
    default:
      jj_la1[47] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    variavel = jj_consume_token(VAR);
                tabela.insereSimboloNaTabela(variavel, tipo);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ATRIB:
      atrib = jj_consume_token(ATRIB);
      expressao = iniciaExpressao(tabela);
                        AcoesSemanticas.incompatibilidadeTipoAtribuicao (tabela.pesquisarSimboloTabela(variavel.image), expressao, variavel);
                        comando = new ComandoAtribuicao(tabela.pesquisarSimboloTabela(variavel.image), expressao, atrib);
                        tabela.pesquisarSimboloTabela(variavel.image).setIsInicializada(true);
                        AcoesSemanticas.faltaInicializacaoVariavel(expressao,tabela, variavel);
                        listaComandosAltoNivel.addComando(comando);
      break;
    default:
      jj_la1[48] = jj_gen;
      ;
    }
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRGULA:
        ;
        break;
      default:
        jj_la1[49] = jj_gen;
        break label_14;
      }
      jj_consume_token(VIRGULA);
      variavel = jj_consume_token(VAR);
                        tabela.insereSimboloNaTabela(variavel, tipo);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ATRIB:
        atrib = jj_consume_token(ATRIB);
        expressao = iniciaExpressao(tabela);
                                AcoesSemanticas.incompatibilidadeTipoAtribuicao (tabela.pesquisarSimboloTabela(variavel.image), expressao, variavel);
                                comando = new ComandoAtribuicao(tabela.pesquisarSimboloTabela(variavel.image), expressao, atrib);
                                tabela.pesquisarSimboloTabela(variavel.image).setIsInicializada(true);
                                AcoesSemanticas.faltaInicializacaoVariavel(expressao,tabela,variavel);
                                listaComandosAltoNivel.addComando(comando);
        break;
      default:
        jj_la1[50] = jj_gen;
        ;
      }
    }
    jj_consume_token(PV);
  }

  static final public void se(ListaComandosAltoNivel listaComandosAltoNivel, Tabela tabela) throws ParseException {
        Token se,senao;
        ListaComandosAltoNivel listaProgramaSe =  new ListaComandosAltoNivel();
        ListaComandosAltoNivel listaProgramaSenao =  new ListaComandosAltoNivel();
        Expressao expressao = null;
        ComandoAltoNivel  comando = null;
    se = jj_consume_token(SE);
    jj_consume_token(AP);
    expressao = iniciaExpressao(tabela);
    jj_consume_token(FP);
    programa(listaProgramaSe, tabela);
                comando = new ComandoCondicionalSimples(expressao, listaProgramaSe, se);
                AcoesSemanticas.faltaInicializacaoVariavel(expressao,tabela,se);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SENAO:
      senao = jj_consume_token(SENAO);
      programa(listaProgramaSenao, tabela);
            comando = new ComandoCondicionalCompleto(expressao, listaProgramaSe, listaProgramaSenao, se);
      break;
    default:
      jj_la1[51] = jj_gen;
      ;
    }
    jj_consume_token(FIMSE);
          listaComandosAltoNivel.addComando(comando);
  }

  static final public void fazerEnquanto(ListaComandosAltoNivel listaComandosAltoNivel, Tabela tabela) throws ParseException {
        Token fazer;
        ListaComandosAltoNivel listaProgramaFazerEnquanto = new ListaComandosAltoNivel();
        Expressao expressao = null;
        ComandoAltoNivel comando = null;
    fazer = jj_consume_token(FACA);
    programa(listaProgramaFazerEnquanto, tabela);
    jj_consume_token(FAZERENQUANTO);
    jj_consume_token(AP);
    expressao = iniciaExpressao(tabela);
    jj_consume_token(FP);
    jj_consume_token(PV);
                comando = new ComandoFazerEnquanto(expressao, listaProgramaFazerEnquanto, fazer);
                AcoesSemanticas.faltaInicializacaoVariavel(expressao,tabela, fazer);
                listaComandosAltoNivel.addComando(comando);
  }

  static final public void enquanto(ListaComandosAltoNivel listaComandosAltoNivel, Tabela tabela) throws ParseException {
        Token enq;
        ListaComandosAltoNivel listaProgramaEnquanto = new ListaComandosAltoNivel();
        Expressao expressao = null;
        ComandoAltoNivel comando = null;
    enq = jj_consume_token(ENQUANTO);
    jj_consume_token(AP);
    expressao = iniciaExpressao(tabela);
    jj_consume_token(FP);
    programa(listaProgramaEnquanto, tabela);
                comando = new ComandoEnquanto(expressao, listaProgramaEnquanto, enq);
                AcoesSemanticas.faltaInicializacaoVariavel(expressao,tabela,enq);
                listaComandosAltoNivel.addComando(comando);
    jj_consume_token(FIMENQUANTO);
  }

  static final public void le(ListaComandosAltoNivel listaComandosAltoNivel, Tabela tabela) throws ParseException {
        Token le, t;
        ComandoAltoNivel comando = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LEITURA:
      le = jj_consume_token(LEITURA);
      break;
    case LEITURACOMPLETA:
      le = jj_consume_token(LEITURACOMPLETA);
      t = jj_consume_token(STRING);
      jj_consume_token(VIRGULA);
                        Expressao expressao = new Expressao(tabela.getNome());
                        Item string = new Operando( TipoDado.PALAVRA, TipoElemento.CTE, t, Sinal.POS );
                        expressao.addListaExpInfixa( string );
                        expressao.addListaExpPosFixa( string );
                    comando  = new ComandoSaida( expressao, le );
                    listaComandosAltoNivel.addComando( comando );
      break;
    default:
      jj_la1[52] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    t = jj_consume_token(VAR);
                comando = new ComandoEntrada(tabela.pesquisarSimboloTabela(t.image), le);
                tabela.pesquisarSimboloTabela(t.image).setIsInicializada(true);
                tabela.pesquisarSimboloTabela(t.image).setIsUtilizada(true);
                listaComandosAltoNivel.addComando(comando);
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRGULA:
        ;
        break;
      default:
        jj_la1[53] = jj_gen;
        break label_15;
      }
      jj_consume_token(VIRGULA);
      t = jj_consume_token(VAR);
                        comando = new ComandoEntrada(tabela.pesquisarSimboloTabela(t.image), le);
                        tabela.pesquisarSimboloTabela(t.image).setIsInicializada(true);
                        listaComandosAltoNivel.addComando(comando);
    }
    jj_consume_token(PV);
  }

  static final public void exibe(ListaComandosAltoNivel listaExibe, Tabela tabela) throws ParseException {
        Token exibe;
        boolean novaLinha = false;
        Expressao expressao = null;
        ComandoSaida comando = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EXIBE:
      exibe = jj_consume_token(EXIBE);
      break;
    case EXIBELN:
      exibe = jj_consume_token(EXIBELN);
                                                novaLinha = true;
      break;
    default:
      jj_la1[54] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    expressao = iniciaExpressao(tabela);
                comando = new ComandoSaida(expressao, exibe);
                AcoesSemanticas.faltaInicializacaoVariavel(expressao,tabela,exibe);
                listaExibe.addComando(comando);
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRGULA:
        ;
        break;
      default:
        jj_la1[55] = jj_gen;
        break label_16;
      }
      jj_consume_token(VIRGULA);
      expressao = iniciaExpressao(tabela);
                        comando = new ComandoSaida(expressao, exibe);
                        AcoesSemanticas.faltaInicializacaoVariavel(expressao,tabela,exibe);
                        listaExibe.addComando(comando);
    }
    jj_consume_token(PV);
                if ( novaLinha ) AcoesSemanticas.adicionarQuebraLinha( listaExibe, tabela.getNome(), exibe );
  }

  static final public void para(ListaComandosAltoNivel listaComandosAltoNivel, Tabela tabela) throws ParseException {
        Token tokenPara;
        ListaComandosAltoNivel listaProgramaPara = new ListaComandosAltoNivel();
        Expressao expressao = null;
        ComandoAltoNivel comando = null;
        ListaComandosAltoNivel listaAtribuicaoInicio = new ListaComandosAltoNivel();
        ListaComandosAltoNivel listaAtribuicaoPasso = new ListaComandosAltoNivel();
    tokenPara = jj_consume_token(PARA);
    jj_consume_token(AP);
    atribuicaoChamada(listaAtribuicaoInicio, tabela);
    jj_consume_token(PV);
    expressao = iniciaExpressao(tabela);
    jj_consume_token(PV);
    atribuicaoChamada(listaAtribuicaoPasso, tabela);
    jj_consume_token(FP);
    programa(listaProgramaPara, tabela);
    jj_consume_token(FIMPARA);
                comando = new ComandoPara(listaAtribuicaoInicio, expressao, listaAtribuicaoPasso, listaProgramaPara, tokenPara);
                AcoesSemanticas.faltaInicializacaoVariavel(expressao,tabela, tokenPara);
                listaComandosAltoNivel.addComando(comando);
  }

  static final public void seletor(ListaComandosAltoNivel listaComandosAltoNivel, Tabela tabela) throws ParseException {
        Token tokenSeletor, tokenEntrada;
        Item itemCaso = null;
        Expressao expressaoSeletor = null;
        ComandoAltoNivel comando = null;
        ListaComandosAltoNivel listaPrograma = new ListaComandosAltoNivel();
        LinkedList<ListaComandosAltoNivel> listaComandosAltoNivelCasos = new LinkedList<ListaComandosAltoNivel>();
        LinkedList<Item> listaOpcaoCasos = new LinkedList<Item>();
    tokenSeletor = jj_consume_token(SELETOR);
    jj_consume_token(AP);
    expressaoSeletor = iniciaExpressao(tabela);
    jj_consume_token(FP);
    label_17:
    while (true) {
      jj_consume_token(CASO);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUM:
        tokenEntrada = jj_consume_token(NUM);
                                      itemCaso = new Operando(TipoDado.NUMERO,TipoElemento.CTE, tokenEntrada, Sinal.POS);
        break;
      case SOMA:
        jj_consume_token(SOMA);
        tokenEntrada = jj_consume_token(NUM);
                                              itemCaso = new Operando(TipoDado.NUMERO,TipoElemento.CTE, tokenEntrada, Sinal.POS);
        break;
      case SUB:
        jj_consume_token(SUB);
        tokenEntrada = jj_consume_token(NUM);
                                             itemCaso = new Operando(TipoDado.NUMERO,TipoElemento.CTE, tokenEntrada, Sinal.NEG);
        break;
      default:
        jj_la1[56] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(DP);
      programa(listaPrograma, tabela);
          listaComandosAltoNivelCasos.add(listaPrograma);
          listaOpcaoCasos.add(itemCaso);
          listaPrograma = new ListaComandosAltoNivel();
      jj_consume_token(FIMCASO);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CASO:
        ;
        break;
      default:
        jj_la1[57] = jj_gen;
        break label_17;
      }
    }
          comando = new ComandoSeletor(expressaoSeletor, listaComandosAltoNivelCasos, listaOpcaoCasos, token);
          AcoesSemanticas.faltaInicializacaoVariavel(expressaoSeletor,tabela, tokenSeletor);
          listaComandosAltoNivel.addComando(comando);
    jj_consume_token(FIMSELETOR);
  }

  static final public void repeat(ListaComandosAltoNivel listaComandosAltoNivel, Tabela tabela) throws ParseException {
        Token tokenRepeat, tokenNumero;
        ListaComandosAltoNivel listaProgramaRepeat = new ListaComandosAltoNivel();
        ComandoAltoNivel comando = null;
        Item item;
    tokenRepeat = jj_consume_token(REPEAT);
    jj_consume_token(AP);
    tokenNumero = jj_consume_token(NUM);
      item = new Operando(TipoDado.NUMERO,TipoElemento.CTE, tokenNumero, Sinal.POS);
    jj_consume_token(FP);
    programa(listaProgramaRepeat, tabela);
    jj_consume_token(FIMREPEAT);
      comando = new ComandoRepeat(listaProgramaRepeat, tokenRepeat, item);
          listaComandosAltoNivel.addComando(comando);
  }

  static final public void seRepete(ListaComandosAltoNivel listaComandosAltoNivel, Tabela tabela) throws ParseException {
        Token se_repete, token_repete_n;
        Expressao exp = null;
        Item item;
        ListaComandosAltoNivel lista_escopo_SeRepete = new ListaComandosAltoNivel();
        ComandoAltoNivel comando = null;
    se_repete = jj_consume_token(SEREPETE);
    jj_consume_token(AP);
    exp = iniciaExpressao(tabela);
    jj_consume_token(VIRGULA);
    token_repete_n = jj_consume_token(NUM);
                item = new Operando(TipoDado.NUMERO,TipoElemento.CTE, token_repete_n, Sinal.POS);
    jj_consume_token(FP);
    programa(lista_escopo_SeRepete, tabela);
                comando = new ComandoSeRepete(exp, token_repete_n, item, lista_escopo_SeRepete);
                AcoesSemanticas.faltaInicializacaoVariavel(exp, tabela, se_repete);
                listaComandosAltoNivel.addComando(comando);
    jj_consume_token(FIMSEREPETE);
  }

  static final public void duplo(ListaComandosAltoNivel listaComandosAltoNivel, Tabela tabela) throws ParseException {
        Token tokenDuplo;
        ListaComandosAltoNivel listaProgramaDuplo = new ListaComandosAltoNivel();
        ComandoAltoNivel comando = null;
    tokenDuplo = jj_consume_token(DUPLO);
    programa(listaProgramaDuplo, tabela);
        comando = new ComandoDuplo(listaProgramaDuplo, tokenDuplo);
                listaComandosAltoNivel.addComando(comando);
    jj_consume_token(FIMDUPLO);
  }

// Tarefa 18
  static final public void matrix3D(ListaComandosAltoNivel listaMatrix3D, Tabela tabela) throws ParseException {
        Token tokenMatrix3D, tokenVarDimX, tokenVarDimY, tokenVarDimZ, tokenCteInit, tokenCteLimSup;
        ComandoAltoNivel comandoMatrix3D = null;
        Item cteInicializacao = null;
        Item cteLimiteSuperior = null;
        Expressao expInicializacao = new Expressao(tabela.getNome());
        Expressao expCondicaoParada = new Expressao(tabela.getNome());
        ListaComandosAltoNivel blocoComandosMatrix = new ListaComandosAltoNivel();
    tokenMatrix3D = jj_consume_token(MATRIX3D);
    jj_consume_token(AP);
    tokenVarDimX = jj_consume_token(VAR);
                                  if ( !tabela.verificarNamespace( tokenVarDimX.image ) ) tabela.insereSimboloNaTabela( tokenVarDimX, TipoDado.NUMERO );
                                  tabela.pesquisarSimboloTabela( tokenVarDimX.image ).setIsInicializada(true);
    jj_consume_token(VIRGULA);
    tokenVarDimY = jj_consume_token(VAR);
                                  if ( !tabela.verificarNamespace( tokenVarDimY.image ) ) tabela.insereSimboloNaTabela( tokenVarDimY, TipoDado.NUMERO );
                                  tabela.pesquisarSimboloTabela( tokenVarDimY.image ).setIsInicializada(true);
    jj_consume_token(VIRGULA);
    tokenVarDimZ = jj_consume_token(VAR);
                                  if ( !tabela.verificarNamespace( tokenVarDimZ.image ) ) tabela.insereSimboloNaTabela( tokenVarDimZ, TipoDado.NUMERO );
                                  tabela.pesquisarSimboloTabela( tokenVarDimZ.image ).setIsInicializada(true);
    jj_consume_token(SUB);
    tokenCteInit = jj_consume_token(NUM);
                                  cteInicializacao = new Operando( TipoDado.NUMERO, TipoElemento.CTE, tokenCteInit, Sinal.POS );
                                  expInicializacao.addListaExpInfixa( cteInicializacao );
                                  expInicializacao.addListaExpPosFixa( cteInicializacao );
    jj_consume_token(TO);
    tokenCteLimSup = jj_consume_token(NUM);
                                  cteLimiteSuperior = new Operando( TipoDado.NUMERO, TipoElemento.CTE, tokenCteLimSup, Sinal.POS );
                                  expCondicaoParada.addListaExpInfixa( cteLimiteSuperior );
                                  expCondicaoParada.addListaExpPosFixa( cteLimiteSuperior );
    jj_consume_token(FP);
    programa(blocoComandosMatrix, tabela);
    jj_consume_token(FIMMATRIX3D);
                                        comandoMatrix3D = new ComandoMatrix3D( tabela.getNome(), tokenMatrix3D, tokenVarDimX, tokenVarDimY, tokenVarDimZ, expInicializacao, expCondicaoParada, blocoComandosMatrix );
                                        listaMatrix3D.addComando( comandoMatrix3D );
  }

  static final public void ternario(ListaComandosAltoNivel listaTernario , Tabela tabela) throws ParseException {
        Token tokenTernario;
        Expressao expressao;
        ListaComandosAltoNivel listaTernarioTrue = new ListaComandosAltoNivel();
        ListaComandosAltoNivel listaTernarioFalse = new ListaComandosAltoNivel();
        ComandoAltoNivel comandoCondicionalCompleto;
    jj_consume_token(AP);
    expressao = iniciaExpressao(tabela);
    jj_consume_token(FP);
    tokenTernario = jj_consume_token(TERNARIO);
    jj_consume_token(AC);
    programa(listaTernarioTrue, tabela);
    jj_consume_token(FC);
    jj_consume_token(DP);
    jj_consume_token(AC);
    programa(listaTernarioFalse, tabela);
    jj_consume_token(FC);
                comandoCondicionalCompleto = new ComandoCondicionalCompleto( expressao, listaTernarioTrue, listaTernarioFalse, tokenTernario );
                listaTernario.addComando( comandoCondicionalCompleto );
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public CompiladorTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[58];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x55454f00,0x55454f00,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1000,0x600,0x0,0x100,0x0,0x0,0x100000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x600000,0x600000,0x1000000,0xd8000000,0xd8000000,0x9c7003,0x20000000,0x6000,0x6000,0x18000,0x18000,0x20000,0x1c0000,0x3,0x1c0003,0x1c7003,0x6000,0x6000,0x0,0x0,0x1000,0x7000,0x124,0x124,0x80,0x600,0x0,0x600,0x600,0x600,0x600,0x0,0x600,0x600,0x600,0x600,0x710,0x710,0x700,0x601e000,0x0,0x9c7003,0x0,0x0,0x6000000,0x1e000,0x601e000,0x600,0x2000000,0x0,0x2000000,0x0,0x0,0x0,0x0,0x0,0x7000,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x1810,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1810,0x0,0x0,0x400,0x10,0x1000,0x1810,0x0,0x0,0x1000,0x0,0x400,0x0,0x0,0x0,0x0,0x400,0x0,0x0,0x0,0x0,0x1012,0x1012,0x1000,0x410,0x400,0x1810,0x400,0x400,0x400,0x0,0x400,0x0,0x0,0x400,0x0,0x0,0x0,0x400,0x2,0x400,0x0,0x0,};
   }

  /** Constructor with InputStream. */
  public Compilador(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Compilador(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CompiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Compilador(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new CompiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Compilador(CompiladorTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CompiladorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[77];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 58; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 77; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
