/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIBE = 8;
  /** RegularExpression Id. */
  int LEITURA = 9;
  /** RegularExpression Id. */
  int SE = 10;
  /** RegularExpression Id. */
  int SENAO = 11;
  /** RegularExpression Id. */
  int FIMSE = 12;
  /** RegularExpression Id. */
  int ENQUANTO = 13;
  /** RegularExpression Id. */
  int FIMENQUANTO = 14;
  /** RegularExpression Id. */
  int PARA = 15;
  /** RegularExpression Id. */
  int FIMPARA = 16;
  /** RegularExpression Id. */
  int SELETOR = 17;
  /** RegularExpression Id. */
  int FIMSELETOR = 18;
  /** RegularExpression Id. */
  int CASO = 19;
  /** RegularExpression Id. */
  int FIMCASO = 20;
  /** RegularExpression Id. */
  int FACA = 21;
  /** RegularExpression Id. */
  int FAZERENQUANTO = 22;
  /** RegularExpression Id. */
  int REPEAT = 23;
  /** RegularExpression Id. */
  int FIMREPEAT = 24;
  /** RegularExpression Id. */
  int SEREPETE = 25;
  /** RegularExpression Id. */
  int FIMSEREPETE = 26;
  /** RegularExpression Id. */
  int DUPLO = 27;
  /** RegularExpression Id. */
  int FIMDUPLO = 28;
  /** RegularExpression Id. */
  int MATRIX3D = 29;
  /** RegularExpression Id. */
  int FIMMATRIX3D = 30;
  /** RegularExpression Id. */
  int COMENTLINHA = 31;
  /** RegularExpression Id. */
  int NUMERO = 32;
  /** RegularExpression Id. */
  int PALAVRA = 33;
  /** RegularExpression Id. */
  int DIGIT = 34;
  /** RegularExpression Id. */
  int NUM = 35;
  /** RegularExpression Id. */
  int SOMA = 36;
  /** RegularExpression Id. */
  int SUB = 37;
  /** RegularExpression Id. */
  int MUL = 38;
  /** RegularExpression Id. */
  int DIV = 39;
  /** RegularExpression Id. */
  int POT = 40;
  /** RegularExpression Id. */
  int OU = 41;
  /** RegularExpression Id. */
  int OUEXCLUSIVO = 42;
  /** RegularExpression Id. */
  int NEGACAO = 43;
  /** RegularExpression Id. */
  int E = 44;
  /** RegularExpression Id. */
  int ATRIB = 45;
  /** RegularExpression Id. */
  int ATRIBMULT = 46;
  /** RegularExpression Id. */
  int IGUAL = 47;
  /** RegularExpression Id. */
  int DIFERENTE = 48;
  /** RegularExpression Id. */
  int CONCAT = 49;
  /** RegularExpression Id. */
  int MENOR = 50;
  /** RegularExpression Id. */
  int MAIORIGUAL = 51;
  /** RegularExpression Id. */
  int TO = 52;
  /** RegularExpression Id. */
  int EXIBELN = 53;
  /** RegularExpression Id. */
  int CHAR = 54;
  /** RegularExpression Id. */
  int AP = 55;
  /** RegularExpression Id. */
  int FP = 56;
  /** RegularExpression Id. */
  int AC = 57;
  /** RegularExpression Id. */
  int FC = 58;
  /** RegularExpression Id. */
  int PV = 59;
  /** RegularExpression Id. */
  int DP = 60;
  /** RegularExpression Id. */
  int VIRGULA = 61;
  /** RegularExpression Id. */
  int STRING = 62;
  /** RegularExpression Id. */
  int VAR = 63;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int comentarioGeral = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"exibe\"",
    "\"le\"",
    "\"se\"",
    "\"senao\"",
    "\"fim-se\"",
    "\"enquanto\"",
    "\"fim-enquanto\"",
    "\"para\"",
    "\"fim-para\"",
    "\"seletor\"",
    "\"fim-seletor\"",
    "\"caso\"",
    "\"fim-caso\"",
    "\"faca\"",
    "\"fazer-enquanto\"",
    "\"repeat\"",
    "\"fim-repeat\"",
    "\"se-repete\"",
    "\"fim-se-repete\"",
    "\"duplo\"",
    "\"fim-duplo\"",
    "\"matrix3D\"",
    "\"fim-matrix3D\"",
    "<COMENTLINHA>",
    "\"numero\"",
    "\"palavra\"",
    "<DIGIT>",
    "<NUM>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"OU\"",
    "\"XOU\"",
    "\"NAO\"",
    "\"E\"",
    "\"<-\"",
    "\"<==\"",
    "\"=\"",
    "\"!=\"",
    "\"&\"",
    "\"<\"",
    "\">=\"",
    "\"to\"",
    "\"exibeln\"",
    "<CHAR>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "<STRING>",
    "<VAR>",
  };

}
